-- what is the total revenue generated by  male vs female customer?
SELECT gender , sum(purchase_amount) as revenue from shopping_data
group by gender ;

-- which customer used a discount but still spent more than the average purchase amount 
Select customer_id , purchase_amount from shopping_data
where discount_applied = 'Yes' and purchase_amount >= (select avg(purchase_amount) from shopping_data);

-- which are the top five product with highest average review rating 
select item_purchased , avg(review_rating) as avg_rating from shopping_data
group by item_purchased
order by avg_rating desc limit 5;

-- compare the average purchase amounts between standard and express shipping 
select shipping_type , avg(purchase_amount) from shopping_data
where shipping_type in ( 'Express' , 'Standard')
group by shipping_type;

-- do subscribed customers spend more ? compare average spend and total revenue between subscribers and non-subscribers
select avg(purchase_amount) as 'avg_spend', sum(purchase_amount) as 'total_revenue' ,
subscription_status , count(customer_id) as 'total_customer' from shopping_data
group by subscription_status
order by avg_spend , total_revenue;

-- which 5 products have the highest percentage of puchases with discounts applied?
select item_purchased , 
(100* sum(case 
	when discount_applied = 'Yes' 
    then 1 else 0 
    end) / count(*)) as 'discount_rate' from shopping_data
group by item_purchased 
order by discount_rate desc  limit 5;

-- segment  customers into new , returning and loyal based on their total
-- number of previous purchases and show the count of each segment 
with customer_type as (select customer_id , previous_purchases ,
                    case when previous_purchases <= 1 then 'New' 
                    when previous_purchases between 2 and 10 then 'Returning'
                    else 'Loyal' end as customer_segment from shopping_data)
	select customer_segment ,count(*) as 'number of customer' from customer_type
    group by customer_segment;
                    
-- what are the top 3 most purchased products within each category 
with  item_counts as (select item_purchased , category , count(customer_id) as 'total_orders' ,
row_number() over(partition by category order by count(customer_id ) desc) as item_rank
from shopping_data
group by category , item_purchased)
select item_rank , category , item_purchased,total_orders
from item_counts
where item_rank<=3;

-- are customers who are repeat buyers (more than 5 previous purchased ) also likely to subcribe ?
select subscription_status , count(customer_id) as 'repeat_buyers'  from shopping_data
where previous_purchases > 5 
group by subscription_status;

-- what is the revenue contribution of each age group 
select age_group , sum(purchase_amount) as 'total_revenue' from shopping_data 
group by age_group 
order by total_revenue desc;

                         
 

